apiVersion: v1
kind: Service
metadata:
  name: minha-aplicacao
spec:
  selector:
    app: minha-aplicacao
  ports:
    - port: 80 # Porta do serviço
      targetPort: 80 # Porta do contêiner (ajuste conforme sua aplicação)
      nodePort: 30080 # Porta acessível externamente (30000-32767)
  type: NodePort # Tipo de serviço para acesso externo
